name: OpenJoinMessage
version: '${project.version}'
main: me.hxli.openjoinmessage.OpenJoinMessage
api-version: '1.20'
commands:
  ojm:
    description: An open source plugin that lets you customize player log messages
    aliases: [ojm, openjoinmessage, logmessage, playerlog]
    permission: permission.node